import { BiLogIn } from 'react-icons/bi';
import { type User } from 'wasp/entities';
import { useAuth } from 'wasp/client/auth'; // Importez useAuth pour récupérer les informations sur l'utilisateur


import {
  useQuery, 
} from 'wasp/client/operations';

function LocalProducersMap() {

    return (
      <div className='py-10 lg:mt-10'>
      <div className='mx-auto max-w-7xl px-6 lg:px-8'>
        <div className='mx-auto max-w-4xl text-center'>
          <h2 className='mt-2 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl dark:text-white'>
            <p><span className='text-yellow-500'>Engageons</span>  nous vers un commerce local</p>
          </h2>
        </div>
        <p className='mx-auto mt-6 max-w-2xl text-center text-lg leading-8 text-gray-600 dark:text-white'>
        Our aim is to bring together local businesses and producers in our regions. 
        Let's take advantage of the momentum generated by major companies to help our region and our talents grow!
        It's up to you! 
        </p>
        {/* begin Display of Producers Picture */}
        <div className='my-8 border rounded-3xl border-gray-900/10 dark:border-gray-100/10'>
          <div className='sm:w-[90%] md:w-[70%] lg:w-[50%] py-10 px-6 mx-auto my-8 space-y-10'>
             Pictures of Random Producers with their names, age, picture : goto ProducersPage 
          </div>
        </div>
        {/* end AI-powered Todo List */}
      </div>
    </div>
    );
}
  
export default LocalProducersMap;